### PR TITLE
Expectations don't work with extra code

### LINKED ISSUE #32: Expectations don't work when the exercise has extra code
Gobstones' compiler can't generate the AST of an incomplete program, it fails if any procedure is not defined. Right now, the `ExpectationsRunner` only receives the submitted code but not the extra, and therefore the full program is not available and the AST cannot be generated.

@flbulgarelli should we add a new parameter to `ExpectationsRunner#run_expectations!` and invoke the compiler in the runner? or should we pass the compiled code directly from Mumukit? I think the last one could break another runners.

### PR DESCRIPTION
**Pull request by faloi**
Fixes #32 
To be merged after https://github.com/mumuki/mumukit/pull/7

### CODE REVIEW

File: lib/expectations_runner.rb [hunk 1]
```diff
@@ -29,8 +30,9 @@ class ExpectationsRunner
   include Mumukit
   include StonesSpec::WithTempfile
 
-  def run_expectations!(expectations, content)
-    ast = generate_ast!(content)
+  def run_expectations!(expectations, content, extra = '')
+    source = TestCompiler.new.create_compilation!('examples: []', extra, content)[:source]
```
Comment (flbulgarelli) [inline lib/expectations_runner.rb]: Hmm, i would have extracted a third component here, that does just the concatenation. It could be just a mixin, and then both compiler and expectation's runner would include it and use it
